// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Map():Promise<{[key: string]: string}>;

export function MarshalJSON():Promise<Array<number>>;
