// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEditorItems() {
  return window['go']['app']['App']['GetEditorItems']();
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function NewEditorItem(arg1) {
  return window['go']['app']['App']['NewEditorItem'](arg1);
}
