// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy_store} from '../models';

export function GetEditorItems():Promise<Array<proxy_store.ProxyHistoryItem>>;

export function GetHistory():Promise<Array<proxy_store.ProxyHistoryItem>>;

export function NewEditorItem(arg1:number):Promise<void>;
