// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEditorItems() {
  return window['go']['app']['App']['GetEditorItems']();
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function GetHistoryItem(arg1) {
  return window['go']['app']['App']['GetHistoryItem'](arg1);
}

export function NewEditorItem(arg1) {
  return window['go']['app']['App']['NewEditorItem'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['app']['App']['Send'](arg1, arg2);
}

export function UpdateEditorItem(arg1, arg2) {
  return window['go']['app']['App']['UpdateEditorItem'](arg1, arg2);
}
