// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSampleHistory() {
  return window['go']['app']['App']['AddSampleHistory']();
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}
