// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSampleHistory() {
  return window['go']['main']['App']['AddSampleHistory']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetTestData() {
  return window['go']['main']['App']['GetTestData']();
}
